name: boot.img专属编译
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装官方依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-pip android-tools-boot
          pip install vmlinux-to-elf
      - name: 安装NDK编译工具
        uses: Ylarod/setup-ndk-clang@v1
        id: setup-ndk
        with:
          ndk-version: r29
      - name: 下载并解包boot.img
        run: |
          wget "https://github.com/cxlfhx/ghostlock-oneplus/releases/download/boot/boot.img" -O boot.img
          unpackbootimg -i boot.img -o boot_out
      - name: 提取内核符号表
        run: |
          vmlinux-to-elf boot_out/kernel kernel.elf
          nm -n kernel.elf | grep -E ' [TtDd] ' > kallsyms.txt
      - name: 生成偏移并编译
        run: |
          python3 tools/extract_target.py --kallsyms kallsyms.txt
          make NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: ghostlock
          path: ghostlock
